### ISSUE TITLE
Please use tags when release new version

### ISSUE THREAD

**Issue by LeoIannacone** [jsakas/CSSStyleDeclaration#13]
Hello,

I'm from debian/ubuntu world.

We would like to package your module, but we have some problem: our automatic system, which checks for new releases in github, looks for tags in the relative project homepage, but it seems you do not provide them.

Can you please consider to use tags when release a new version of your software?

This is really important for us.

**Comment by fatfisz** [comment]
As far as I can see tags are already being used in this repo (it's been almost 5 years since this issue was created, so a few things have changed since then).
