### ISSUE TITLE
properties.js defines parse function twice

### ISSUE THREAD

**Issue by terrencewwong** [jsakas/CSSStyleDeclaration#44]
In `v0.2.37` the `prepublish` command is producing a `properties.js` file that looks like this (I've added the line number comments):

```
...
function parse(v) { // line 1644
  if (String(v).toLowerCase() === 'auto') {
    return 'auto';
  }

  if (String(v).toLowerCase() === 'inherit') {
    return 'inherit';
  }

  return external_dependency_parsers_0.parseMeasurement(v);
}
...

function parse(v) { // line 5029
  if (String(v).toLowerCase() === 'auto') {
    return 'auto';
  }

  if (String(v).toLowerCase() === 'inherit') {
    return 'inherit';
  }

  return external_dependency_parsers_0.parseMeasurement(v);
}
```

Parsing this file fails when the parser sees the second declaration of `function parse`

```
SyntaxError: Variable 'parse' has already been declared
```

**Comment by denieler** [comment]
Lets do that!

**Comment by dadhikari16** [comment]
@wongterrencew  @denieler Any update when this will be fixed

**Comment by dadhikari16** [comment]
@wongterrencew @denieler Can you please provide an update on this

**Comment by fatfisz** [comment]
The fix that was prepared and closed a few months ago wouldn't prevent such issues from happening in the future. I'll be merging something that should do just that. Should be released within a week or so.
