### ISSUE TITLE
Get to 1.0.0 and start following semantic versioning

### ISSUE THREAD

**Issue by domenic** [jsakas/CSSStyleDeclaration#59]
Right now this project is < 1.0.0 so we have to pin its exact version since there is no guarantee of it only changing in backward-compatible ways. Releasing a 1.0.0 and committing to following semver would be great for dependencies like jsdom, so they could automatically get any backward-compatible improvements without needing to manually roll the version each time.

**Comment by eddies** [comment]
@jsakas with #52 and #62 merged, are you planning to cut a new release? If so, what do you think about a v1.0.0 release for reasons @domenic outlined above?

**Comment by jsakas** [comment]
@eddies I will bump a release today. I was really hoping to do a full re-write using data from MDN before bumping to 1.0.0.

**Comment by domenic** [comment]
Remember that there are a lot of extra positive integers---it's OK if 1.0.0 isn't perfect, as long as it follows semver. There's no problem with upgrading to 2.0.0 a month later.

**Comment by jsakas** [comment]
@domenic good point, I can be a bit of a perfectionist at times ;)

Seeing that I took over this project specifically because I needed updates for jsdom, I will publish 1.0.0. 

Moving forward, you guys can expect semver compatibility. No breaking changes will be introduced as patches, etc.

Thanks!

**Comment by jsakas** [comment]
1.0.0 is now available on npm.

https://github.com/jsakas/CSSStyleDeclaration/releases/tag/v1.0.0
