### ISSUE TITLE
Add support for numeric values passed to ‘border-spacing’, e.g. ‘border-spacing: 0’.

### ISSUE THREAD

**Issue by jansiegel** [jsakas/CSSStyleDeclaration#63]
When providing `0` to `border-spacing`, cssstyle throws a `v.toLowerCase is not a function` error.

I've submitted a pull request back in 2016 (#47), since then, an alternative approach came up (#52), but neither of them have been merged, and this problem still seems to be happening.

**Comment by fatfisz** [comment]
This seems to have been fixed in #52, so I'm closing the issue. Pleasse reopen if the problem persists.
