### ISSUE TITLE
This project needs a better test runner

### ISSUE THREAD

**Issue by jsakas** [jsakas/CSSStyleDeclaration#65]
[nodeunit](https://github.com/caolan/nodeunit) is deprecated. 

Likely to use Jest,  however it would also be nice to write tests that can be run in a browser against different implementations of CSSStyleDeclaration as a smoke test for feature parity between this Node implementation and the Chrome/FF/etc implementations.

**Comment by bennypowers** [comment]
I'll rewrite the tests with `tape` if you merge feature PRs 😉

**Comment by fatfisz** [comment]
I second OP, we'll be going with Jest. No hard feelings against tape, but Jest is more popular and hence it's more likely people will be familiar with it.
