### ISSUE TITLE
Extra comma

### ISSUE THREAD

**Issue by loking** [jsakas/CSSStyleDeclaration#81]
The extra comma here caused this bug in my application: https://github.com/jsakas/CSSStyleDeclaration/blob/master/lib/CSSStyleDeclaration.js#L201

```
/app/node_modules/cssstyle/lib/CSSStyleDeclaration.js:202
       );
       ^

SyntaxError: Unexpected token )
   at createScript (vm.js:56:10)
   at Object.runInThisContext (vm.js:97:10)
```

It works normally as long as I removed the extra comma. Would be great if there could be a quick patch for the issue. Thanks!

**Comment by raimund-schluessler** [comment]
For me now JSDom fails with the same error.

**Comment by Denizzi** [comment]
Exactly the same problem here. I hope @loking s PR will be merged asap.
