### ISSUE TITLE
Version 1.2.0 has unexpected comma

### ISSUE THREAD

**Issue by zombieJ** [jsakas/CSSStyleDeclaration#84]
Here is the error message.
```
xxx/node_modules/cssstyle/lib/CSSStyleDeclaration.js:202
            );
            ^
    SyntaxError: Unexpected token )
```

Here is the related code: https://github.com/jsakas/CSSStyleDeclaration/blob/master/lib/CSSStyleDeclaration.js#L234

**Comment by fatfisz** [comment]
Duplicate of #81.
