### ISSUE TITLE
font-size not covered by the parse function and can set with invalid values

### ISSUE THREAD

**Issue by omriLugasi** [jsakas/CSSStyleDeclaration#90]
According to [this](https://github.com/jsdom/jsdom/issues/2513) issue in [jsDOM](https://github.com/jsdom/jsdom) i figure out that the bug is in the cssStyleDeclertion 

The bug happen because we don't use the parse function to check if the `font-size` is invalid

For example:

```javascript

    var style = new cssstyle.CSSStyleDeclaration();
    style.cssText = 'font-size: 15px'
    style.length // equal 1
    style.cssText = 'font-size: 1r5px'
    style.length // equal 1 (should be 0 because the value [1r5px] is invalid)
```

I already open pull request that solve this issue.

**Comment by jsakas** [comment]
Closed by https://github.com/jsakas/CSSStyleDeclaration/pull/91
